io_tester: fix compilation with yaml-cpp 0.9.0
Fix required because `sstring` defines implicit conversion for both
`std::basic_string_view` and `std::basic_string`.

apps/io_tester/io_tester.cc:651:30: error: use of overloaded operator '<<' is ambiguous
  (with operand types 'Emitter' and 'sstring' (aka 'basic_sstring<char, unsigned int, 15>'))
  651 |             out << YAML::Key << m_name << YAML::Value << *v;
      |             ~~~~~~~~~~~~~~~~ ^  ~~~~~~
external/yaml-cpp+/include/yaml-cpp/emitter.h:211:17: note: candidate function
  211 | inline Emitter& operator<<(Emitter& emitter, const std::string_view& v) {
      |                 ^
external/yaml-cpp+/include/yaml-cpp/emitter.h:215:17: note: candidate function
  215 | inline Emitter& operator<<(Emitter& emitter, const std::string& v) {